### ISSUE TITLE
Upgrade fails to build on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by pjoksanen** [hwdsl2/setup-ipsec-vpn#184]
Trying to upgrade Libreswan 3.20 to 3.21 and this is what I get:

/opt/src/libreswan-3.21/programs/pluto/ikev2_ipseckey.c:29:45: fatal error: ldns/ldns.h: No such file or directory
compilation terminated.
../../../mk/depend.mk:34: recipe for target 'ikev2_ipseckey.o' failed
make[3]: *** [ikev2_ipseckey.o] Error 1
../../mk/program.mk:50: recipe for target 'local-base' failed
make[2]: *** [local-base] Error 2
../mk/targets.mk:82: recipe for target 'recursive-all' failed
make[1]: *** [recursive-all] Error 2
mk/targets.mk:82: recipe for target 'recursive-all' failed
make: *** [recursive-all] Error 2
Error: Libreswan 3.21 failed to build.

**Comment by hwdsl2** [comment]
@pjoksanen Libreswan 3.21 was released yesterday. It may require new
dependencies (such as libldns-dev) which I have not yet had time to test.
For now, please stay on the Libreswan 3.20 version and do not upgrade to
3.21.

**Comment by pjoksanen** [comment]
Ok, looks like there's nothing that needs urgent fixing or new features that I need, so I'll stay with 3.20
